# Generated by Django 4.2 on 2023-04-20 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='iha_kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori_adi', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='iha_marka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka_adi', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='iha_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_adi', models.CharField(max_length=50, unique=True)),
                ('marka_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.iha_marka')),
            ],
        ),
        migrations.CreateModel(
            name='iha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iha_adi', models.CharField(max_length=50, unique=True)),
                ('agirlik', models.FloatField()),
                ('saatlik_fiyati', models.FloatField()),
                ('resim', models.CharField(max_length=500)),
                ('kategori_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.iha_kategori')),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.iha_model')),
            ],
        ),
    ]
