# Generated by Django 4.2 on 2023-04-20 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='kiralama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kiralama_baslangic', models.DateTimeField()),
                ('kiralama_bitis', models.DateTimeField()),
                ('kiralama_ucret', models.FloatField()),
                ('iha_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.iha')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.users')),
            ],
        ),
    ]
